project_name: workflow-watcher
before:
  hooks:
    - go mod tidy
builds:
  - main: ./
    binary: workflow-watcher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "ghcr.io/mostafahussein/{{ .ProjectName }}:{{ .Version }}-amd64"
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/mostafahussein/workflow-watcher"
    - "--label=org.opencontainers.image.authors=Mostafa Hussein <mostafa.hussein91@gmail.com>"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/mostafahussein/{{ .ProjectName }}:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/mostafahussein/workflow-watcher"
      - "--label=org.opencontainers.image.authors=Mostafa Hussein <mostafa.hussein91@gmail.com>"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
source:
  rlcp: true