name: release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Enable experimental features for the Docker
        run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart

      - name: enable docker buildx
        uses: docker/setup-buildx-action@master

      - name: login to gh registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare a release
        run: make build-release

      - name: publish image
        run: make push
        env:
          VERSION: ${{ github.ref_name }}